os:
- osx

# safelist
branches:
  only:
  - master
  - stable
  
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install graphviz; fi
- brew uninstall --force --ignore-dependencies python
- brew install tcl-tk
- brew install python@2 --use-brewed-tk
- brew link python@2 --force

script:
- pip2.7 install py2app
- pip2.7 install lxml
- pip2.7 install sklearn
- pip2.7 install numpy
- pip2.7 install scipy==0.14.0
- pip2.7 install requests
- sudo pip2 install tornado pytz pysam==0.13 xlrd pygments pyPdf rpy2==2.8.0 setuptools requests_toolbelt logging genapi
- sudo pip2 install igraph certifi colorama pandas patsy simplejson statsmodels matplotlib==2.0.0 biopython sqlalchemy
- sudo pip2 install synapseclient ordereddict nose pytest
- PYTHONPATH=/usr/local/lib/python2.7/site-packages /usr/local/bin/pythonw2.7 build_scripts/setup_binary.py py2app
# pip2 install py2app==0.10

after_success:
- echo "After_Success"
- "./push.sh"

env:
  global:
    secure: QLC6AaJ9kCQKkSjse6c1C+NmTOSPVQdMnE8FAEM2k4+LTJ5eNP7D2+bM6Iew2qOC0knwE5Ekfjk43MQmW1Dl/YPb54CkG0tpDjslfMUs2t+lk/HdaPMnhOXSFFvJFMRtMhJFd9zgAUUoBkpgtbRz5YBpIZdBLJIW3fOR4LZgQtU1xS3HawU12F6ch/KI/tmFGM1z6fwCWhcCoEenD/4rLs4B/KVptg7UH5gY8Kx1So/TpWUL543i6MsV+Gtz5yaeDGvZbBRMPwvOSzgKuFvsPEJtpnYhellSrpocYFQLG5Urzli/p5iMsbGUuyAT96ZbVEb5hZtRJe4tGQG9lRizkTTUWr1j8UE9A7B/RYQLT1c3AWKQCZLYjOY4Ogh3k+9Svff5ZCPn7Pp2B2hgcZ4StZzQGYIezc1xCZG39SKaHC/PvQoPk/tVtTBP2ErODViqfhs7a2+UZRPzs8d6wREu0jQSnANIQT2p0QdsqQYpIKlf8rH/ZBtAS614TuZzGbjs+Lws5tpDKK2iNMUaakUFL09WQqy/nlQ+C6M8qUpQwZVAe/EKXVc4jlLXAxx+/oi5fuTnS79m7q9Cvuy72G67tdbpBKGsdv1F7eqWmjmOAsI456GIYr/QpUdx1cjTn48vo6fvczu7fbtObCnRBVOnr2nQ48gUdDfZmQVHUHCc51Y=
